#!/usr/bin/env node
/**
 * Build the MCP Apps card resources.
 *
 * Bundles each widget entry in ui/ as a self-contained browser IIFE
 * (esbuild), inlines it together with the shared theme CSS into the card
 * shell template, and emits src/ui/generated.ts exporting the finished
 * HTML strings. The main tsup build then bundles those strings into
 * dist/index.js, so the published bridge stays a single self-contained
 * file and scripts/build-mcpb.sh keeps working unchanged.
 *
 * The output is generated (gitignored). npm run check, test, and build
 * all run this script first.
 */

import { build } from 'esbuild'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

const WIDGETS = [
  { entry: 'ui/result-card.ts', constName: 'RESULT_CARD_HTML', title: 'Stript result' },
  { entry: 'ui/status-card.ts', constName: 'STATUS_CARD_HTML', title: 'Stript status' },
  { entry: 'ui/restore-card.ts', constName: 'RESTORE_CARD_HTML', title: 'Stript restore' },
]

const template = await readFile(path.join(root, 'ui/card.html'), 'utf8')
const css = await readFile(path.join(root, 'ui/theme.css'), 'utf8')

/** Self-containment gate at build time: the sandboxed iframe must never
 * try to reach the network. Mirrors the test-side guard. */
function assertSelfContained(html, name) {
  // Markup-level checks run with the inline script body removed, minified
  // JS may legitimately contain strings like location.href.
  const markup = html.replace(/<script>[\s\S]*<\/script>/, '<script></script>')
  const offenders = []
  if (/\bsrc\s*=/i.test(markup)) offenders.push('src= attribute')
  if (/\bhref\s*=/i.test(markup)) offenders.push('href= attribute')
  if (/<link\b/i.test(markup)) offenders.push('<link> element')
  if (/@import\b/.test(css) || /@import\b/.test(markup)) offenders.push('@import')
  if (/\burl\s*\(/i.test(css)) offenders.push('url() in theme.css')
  if (offenders.length > 0) {
    console.error(`build-ui: ${name} is not self-contained: ${offenders.join(', ')}`)
    process.exit(1)
  }
}

const parts = [
  '// GENERATED by scripts/build-ui.mjs. Do not edit.',
  '// Self-contained MCP Apps card HTML (inline CSS and JS, no external',
  '// references). Rebuilt by npm run build:ui.',
  '',
]

for (const widget of WIDGETS) {
  const bundle = await build({
    entryPoints: [path.join(root, widget.entry)],
    bundle: true,
    format: 'iife',
    platform: 'browser',
    target: 'es2022',
    minify: true,
    legalComments: 'none',
    write: false,
  })
  const output = bundle.outputFiles?.[0]
  if (output === undefined) {
    console.error(`build-ui: no output for ${widget.entry}`)
    process.exit(1)
  }
  // Standard inline-script escape so a literal never closes the tag early.
  const js = output.text.replace(/<\/script/gi, '<\\/script')
  // Function replacements: minified JS contains $-patterns that a string
  // replacement would expand.
  const html = template
    .replace('__STRIPT_TITLE__', () => widget.title)
    .replace('__STRIPT_STYLE__', () => css.trimEnd())
    .replace('__STRIPT_SCRIPT__', () => js.trimEnd())
  assertSelfContained(html, widget.entry)
  parts.push(`export const ${widget.constName} = ${JSON.stringify(html)}`)
  parts.push('')
}

const outDir = path.join(root, 'src/ui')
await mkdir(outDir, { recursive: true })
await writeFile(path.join(outDir, 'generated.ts'), parts.join('\n'))
console.error(`build-ui: OK. Wrote src/ui/generated.ts (${WIDGETS.length} cards).`)
